# Site settings
author: Robert Fustero
title: Robert Fustero's Blog
header-img: img/home-bg.png
email: robertfustero@gmail.com
copyright_name: Robert Fustero
description: > # this means to ignore newlines until "baseurl:"
  Summaries and Sarcasm
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  fastaro

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
